Models/Company.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CoursesMain.Models
{
    public class Company
    {
        public int id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string video { get; set; }
        public string image { get; set; }
        public string colectedSum { get; set; }
        public string sum { get; set; }
        public string endDate{ get; set; }
        public string createDate { get; set; }
        public string userId { get; set; }
        public int themeId { get; set; }
        public Theme theme { get; set; }
        public User user { get; set; }
    }
}

ViewModels/CompanyViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace CoursesMain.ViewModels
{
    public class CompanyViewModel
    {
        [Required]
        public int id { get; set; }
        [Required]
        public string CompanyName { get; set; }
        [Required]
        public string Theme { get; set; }
        public string[] Themes { get; set; }
        public string Tags { get; set; }
        public string CompanyInfo { get; set; }
        public string CompanyLinkVideo { get; set; }
        public string CompanyLinkImage { get; set; }
        [Required]
        public string Sum { get; set; }
        [Required]
        public string EndDate { get; set; }
    }
}

Controllers/BonusesController.cs
using CoursesMain.Filters;
using CoursesMain.Models;
using CoursesMain.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CoursesMain.Controllers
{
    [TypeFilter(typeof(UserFilter))]
    public class BonusesController : Controller
    {
        private readonly ApplicationContext _db;
        private readonly UserManager<User> _userManager;
        public BonusesController(UserManager<User> userManager, ApplicationContext db)
        {
            _db = db;
            _userManager = userManager;
        }
        [HttpPost]
        public async Task<IActionResult> AddBonus(ShowCompanyViewModel model)
        {
            Company company = _db.Companies.FirstOrDefault(item => item.id == model.Id);
            if (company != null)
            {
                _db.Bonus.Add(new Bonus
                {
                    company = company,
                    name = model.addBonus.Name,
                    description = model.addBonus.Description,
                    sum = model.addBonus.Sum
                });
                await _db.SaveChangesAsync();
            }
            return RedirectToAction(model.Id + "", "Company");
        }
        [HttpPost]
        public async Task<IActionResult> DeleteBonus(ShowCompanyViewModel model)
        {
            _db.Bonus.Remove(_db.Bonus.FirstOrDefault(item => item.id == model.deleteBonusID));
            await _db.SaveChangesAsync();
            return RedirectToAction(model.Id + "", "Company");
        }
        [HttpPost]
        public async Task<IActionResult> Pay(ShowCompanyViewModel model)
        {
            Bonus bonus = _db.Bonus.FirstOrDefault(item => item.id == model.payID);
            if (bonus != null)
            {
                Company company = _db.Companies.FirstOrDefault(item => item.id == bonus.companyID);
                if (company != null)
                {
                    User user = await _userManager.GetUserAsync(User);
                    company.colectedSum = (int.Parse(company.colectedSum) + int.Parse(bonus.sum)) + "";
                    _db.Companies.Update(company);
                    _db.BonusesToUsers.Add(new BonusesToUser { bonus = bonus, user = user });
                    await _db.SaveChangesAsync();
                }
            }
            return RedirectToAction(model.Id + "", "Company");
        }
    }
}

Controllers/CompanyController.cs
using CoursesMain.Filters;
using CoursesMain.Models;
using CoursesMain.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CoursesMain.Controllers
{
    [TypeFilter(typeof(UserFilter))]
    public class CompanyController : Controller
    {
        private readonly ApplicationContext _db;
        private readonly UserManager<User> _userManager;
        public CompanyController(UserManager<User> userManager, ApplicationContext db)
        {
            _db = db;
            _userManager = userManager;
        }
        public async Task<IActionResult> AddCompany()
        {
            User user = await _userManager.GetUserAsync(User);
            _db.Companies.Add(new Company {
                user = user,
                name = "Simple name",
                createDate = DateTime.Now.ToString("MM/dd/yyyy"),
                colectedSum = "0",
                theme = _db.Themes.FirstOrDefault(),
                sum = "0" });
            await _db.SaveChangesAsync();
            return RedirectToAction("Index", "Profile");
        }
        public async Task<IActionResult> DeleteCompany(ProfileViewModel model)
        {
            for (int i = 0; i < model.companies.Length; i++)
            {
                if (model.companies[i].selected)
                {
                    Company company = _db.Companies.FirstOrDefault(item => item.id == model.companies[i].id);
                    _db.Companies.Remove(company);
                    await _db.SaveChangesAsync();
                }
            }
            return RedirectToAction("Index", "Profile");
        }
        [HttpGet]
        public IActionResult EditCompany(ProfileViewModel model)
        {
            for (int i = 0; i < model.companies.Length; i++)
            {
                if (model.companies[i].selected)
                {
                    Company company = _db.Companies.FirstOrDefault(item => item.id == model.companies[i].id);
                    string[] themes = _db.Themes.Select(item => item.name).ToArray();
                    string[] tags = _db.TagsToCompanies.Where(item => item.company == company).Select(item => item.tag.name).ToArray();
                    string tag="";
                    foreach (string buf in tags)
                    {
                        tag += buf+" ";
                    }
                    return View(new CompanyViewModel {
                        id = company.id,
                        CompanyInfo = company.description,
                        CompanyName = company.name,
                        EndDate = company.endDate,
                        Sum = company.sum,
                        Themes = themes,
                        Tags = tag,
                        CompanyLinkImage = company.image,
                        CompanyLinkVideo = company.video });
                }
            }
            return RedirectToAction("Index", "Profile");
        }
        [HttpPost]
        public async Task<IActionResult> EditCompany(CompanyViewModel model)
        {
            Company company = _db.Companies.FirstOrDefault(item => item.id == model.id);
            if (_db.TagsToCompanies.FirstOrDefault(item => item.company == company)!=null)
                _db.TagsToCompanies.RemoveRange(_db.TagsToCompanies.Where(item => item.company == company));
            await _db.SaveChangesAsync();
            company.name = model.CompanyName;
            company.description = model.CompanyInfo;
            company.sum = model.Sum;
            company.endDate = model.EndDate;
            company.theme = _db.Themes.FirstOrDefault(item => item.name == model.Theme);
            company.image = model.CompanyLinkImage;
            company.video = model.CompanyLinkVideo;
            if (model.Tags != null)
            {
                model.Tags = model.Tags.Replace("  ", " ");
                string[] tags = model.Tags.Split(" ");
                _db.Companies.Update(company);
                for (int i = 0; i < tags.Length; i++)
                {
                    if (tags[i] != "")
                    {
                        Tag tag = _db.Tag.FirstOrDefault(item => item.name == tags[i]);
                        if (tag == null)
                        {
                            _db.Tag.Add(new Tag { name = tags[i] });
                            await _db.SaveChangesAsync();
                            _db.TagsToCompanies.Add(new TagsToCompany { company = company, tag = _db.Tag.FirstOrDefault(item => item.name == tags[i]) });
                        }
                        else
                        {
                            _db.TagsToCompanies.Add(new TagsToCompany { company = company, tag = tag });
                        }
                    }
                }
            }
            await _db.SaveChangesAsync();
            return RedirectToAction("Index", "Profile");
        }
        [Route("Company/{id:int}")]
        public async Task<IActionResult> Index(int id)
        {
            Company company = _db.Companies.FirstOrDefault(item => item.id == id);
            if (company != null)
            {
                User user = await _userManager.GetUserAsync(User);
                Mark mark = _db.Marks.FirstOrDefault(item => item.company == company && item.user == user);
                int[] marksAll = _db.Marks.Where(item => item.company == company).Select(item => item.value).ToArray();
                double marksRes = 0;
                if (marksAll.Length > 0)
                {
                    for (int i = 0; i < marksAll.Length; i++)
                    {
                        marksRes += marksAll[i]+1;
                    }
                    marksRes /= marksAll.Length;
                }
                marksRes = Math.Round(marksRes, 2);
                bool[] marks = new bool[5];
                if (mark != null)
                {
                    for (int i = 0; i < 5; i++)
                    {
                        if (i <= mark.value)
                            marks[i] = true;
                        else
                            marks[i] = false;
                    }
                }
                else
                {
                    for (int i = 0; i < 5; i++)
                    {
                        marks[i] = false;
                    }
                }
                string theme = _db.Themes.FirstOrDefault(item => item.id == company.themeId).name;
                string userName = _userManager.Users.FirstOrDefault(item => item.Id == company.userId).UserName;

                NewsView[] news = _db.News.Where(item => item.company == company)
                    .Select(item => new NewsView { Name = item.name, Description = item.description, Image = item.image, id = item.id }).ToArray();

                CommentsView[] comments = _db.Comments.Where(item => item.company == company)
                    .Select(item => new CommentsView { id = item.id, Author = item.user.UserName, Text = item.text, Rating = 0 }).ToArray();

                BonusView[] bonuses = _db.Bonus.Where(item => item.company == company)
                    .Select(item => new BonusView { Name = item.name, Description = item.description, Sum = item.sum, id = item.id }).ToArray();
                for (int i = 0; i < comments.Length; i++)
                {
                    foreach(bool rating in _db.Ratings.Where(item => item.commentId == comments[i].id).Select(item => item.value))
                    {
                        if (rating)
                            comments[i].Rating++;
                        else
                            comments[i].Rating--;
                    }
                }

                return View(new ShowCompanyViewModel {
                    Id = company.id,
                    Name = company.name,
                    Theme = theme,
                    Image = company.image,
                    Description = company.description,
                    Video = company.video,
                    mark = marks,
                    marks = marksRes,
                    User = userName,
                    news = news,
                    addNews = new NewsView(),
                    comments = comments,
                    bonuses = bonuses,
                    addBonus = new BonusView()
                });

            }
            else return View("NotFound");
        }
        [HttpPost]
        public async Task<IActionResult> SetMark(ShowCompanyViewModel model)
        {
            User user = await _userManager.GetUserAsync(User);
            Company company = _db.Companies.FirstOrDefault(item => item.id == model.Id);
            Mark mark = _db.Marks.FirstOrDefault(item => item.company == company && item.user == user);
            for (int i = 4; i >= 0; i--)
            {
                if (model.mark[i]==true)
                {
                    if (mark == null)
                    {
                        _db.Marks.Add(new Mark { company = company, user = user, value = i });
                        await _db.SaveChangesAsync();
                        return RedirectToAction(model.Id + "", "Company");
                    }else
                    {
                        mark.value = i;
                        _db.Marks.Update(mark);
                        await _db.SaveChangesAsync();
                        return RedirectToAction(model.Id + "", "Company");
                    }
                }
            }
            if (mark != null)
            {
                _db.Marks.Remove(mark);
                await _db.SaveChangesAsync();
            }
            return RedirectToAction(model.Id + "", "Company");
        }
    }
}

Controllers/NewsController.cs
using CoursesMain.Filters;
using CoursesMain.Models;
using CoursesMain.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CoursesMain.Controllers
{
    [TypeFilter(typeof(UserFilter))]
    public class NewsController : Controller
    {
        private readonly ApplicationContext _db;
        private readonly UserManager<User> _userManager;
        public NewsController(UserManager<User> userManager, ApplicationContext db)
        {
            _db = db;
            _userManager = userManager;
        }
        [HttpPost]
        public async Task<IActionResult> AddNews(ShowCompanyViewModel model)
        {
            Company company = _db.Companies.FirstOrDefault(item => item.id == model.Id);
            if (company != null)
            {
                _db.News.Add(new News
                {
                    company = company,
                    name = model.addNews.Name,
                    description = model.addNews.Description,
                    image = model.addNews.Image
                });
                await _db.SaveChangesAsync();
            }
            return RedirectToAction(model.Id+"", "Company");
        }
        [HttpPost]
        public async Task<IActionResult> DeleteNews(ShowCompanyViewModel model)
        {
            _db.News.Remove(_db.News.FirstOrDefault(item => item.id == model.deleteNewsID));
            await _db.SaveChangesAsync();
            return RedirectToAction(model.Id + "", "Company");
        }
    }
}

Views/Company/EditCompany.cshtml
@model CompanyViewModel

@{
    ViewBag.Title = "Edit company";
}


<div class="validation" asp-validation-summary="ModelOnly"></div>
<form name="EditCompany" class="" method="post" asp-controller="Company" asp-action="EditCompany">
    <h1 class="h3 mb-3 font-weight-normal">Edit company: @Model.CompanyName</h1>

    <label asp-for="CompanyName" class="text-muted mt-3"></label>
    <input asp-for="CompanyName" class="form-control col-md-6" placeholder="Name">
    <span asp-validation-for="CompanyName" class="d-block"></span>

    <label asp-for="CompanyInfo" class="text-muted mt-3"></label>
    <textarea rows=15 asp-for="CompanyInfo" class="form-control" placeholder="Description"></textarea>
    <span asp-validation-for="CompanyInfo" class="d-block"></span>

    <label asp-for="Sum" class="text-muted mt-3"></label>
    <input type="number" asp-for="Sum" class="form-control col-md-6" placeholder="Sum">
    <span asp-validation-for="Sum" class="d-block"></span>

    <label asp-for="EndDate" class="text-muted mt-3"></label>
    <input type="date" asp-for="EndDate" class="form-control col-md-6" placeholder="End date">
    <span asp-validation-for="EndDate" class="d-block"></span>

    <label asp-for="Tags" class="text-muted mt-3"></label>
    <input asp-for="Tags" class="form-control col-md-6" placeholder="Tags">
    <span asp-validation-for="Tags" class="d-block"></span>

    <label asp-for="Theme" class="text-muted mt-3"></label>
    <select class="form-control field-input mb-5 col-md-6" asp-for="Theme">
        <option value="">Select Industries...</option>
        @for (int i = 0; i < Model.Themes.Length; i++)
        {
            <option value="@Model.Themes[i]">@Model.Themes[i]</option>
        }
    </select>

    <input value="" placeholder="Youtube URL" name="company_video" class="form-control mb-3 col-md-6" />
    <a class="btn btn-default btn-primary mb-3" href="#" id="company_video_apply">Add</a>
    <div class="company-video-preview" id="js-video-preview">
        <iframe id="embedded_video" width="100%" height="200" src="@Model.CompanyLinkVideo" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    </div>

    <a class="btn btn-default btn-primary mb-3" onclick="document.querySelector('.image-loader').click()" href="#">Load image</a>
    <input class="image-loader" style="visibility: collapse; width: 0px;" type="file" onchange="upload(this.files[0])">
    <img class="company-image d-block" style="max-width: 300px; max-height: 150px;" src="@Model.CompanyLinkImage" />
    
    <input asp-for="id" hidden />
    <input id="company-video" asp-for="CompanyLinkVideo" hidden />
    <input id="company-image" asp-for="CompanyLinkImage" hidden />

    <button class="btn btn-lg btn-primary btn-block mt-3 mb-3" type="submit">Save</button>
</form>


<script>
    let CompanyVideoApply = document.getElementById("company_video_apply");
    CompanyVideoApply.addEventListener("click", function (e) {
        e.preventDefault();
        let video = document.getElementById("embedded_video");
        let reg = /v=\w{11}/;
        let buf = "https://www.youtube.com/embed/" + reg.exec(EditCompany.company_video.value)[0].slice(2);

        video.src = buf;
        document.getElementById("company-video").setAttribute('value', buf);
    });

    let inputTag = document.getElementById("tag");
    function GetTags() {
        let elements = document.querySelectorAll('ul > li');
        elements.forEach(item => {
            item.remove();
        });
        let arr = inputTag.value.split(' ');
        for (let i = 0; i < arr.length; i++) {
            if (arr[i].trim() !== '') {
                let CompanyKeywordsList = document.getElementById("company-keywords-list");
                let li = document.createElement('LI');
                li.innerHTML = arr[i];
                CompanyKeywordsList.appendChild(li);
            }
        }
    }

    window.ondragover = function (e) { e.preventDefault() }
    window.ondrop = function (e) { e.preventDefault(); upload(e.dataTransfer.files[0]); }
    function upload(file) {

        if (!file || !file.type.match(/image.*/)) return;

        let spanUploading = document.createElement('div');
        spanUploading.classList.add("fixed-bottom");
        spanUploading.innerHTML = "Uploading";
        document.body.appendChild(spanUploading);



        var fd = new FormData();
        fd.append("image", file);
        var xhr = new XMLHttpRequest();
        xhr.open("POST", "https://api.imgur.com/3/image.json");
        xhr.onload = function () {
            let linkImage = JSON.parse(xhr.responseText).data.link;
            document.querySelector('.company-image').src = linkImage;

            document.getElementById("company-image").setAttribute('value', linkImage);

            spanUploading.innerHTML = "uploaded";
        }

        xhr.setRequestHeader('Authorization', 'Client-ID 28aaa2e823b03b1');

        xhr.send(fd);
    }
</script>

Views/Company/Index.cshtml
@model ShowCompanyViewModel
@{
    ViewBag.Title = "Home Page";
}
<script>
    let userName = "@User.Identity.Name";
    let company = "@Model.Id";
    let text = "@Model.Description".replace(/&#xD;&#xA;/g, "\n");
</script>
<div class="d-flex p-3 border align-items-center">
    <img src="@Model.Image" width="350px" />
    <div class="ml-3">
        <h1>@Model.Name</h1>
        <h3 class="text-muted">Theme: @Model.Theme</h3>
        <h5 class="text-muted">Creator: @Model.User</h5>
        <h5 class="text-muted">Rating: @Model.marks</h5>
        <form asp-action="SetMark" asp-controller="Company" class="d-flex align-items-center" method="post">
            <label class="m-0 mr-3">Estimate: </label>
            @for (int i = 0; i < Model.mark.Length; i++)
            {
                string buf = "check" + i;
                if (Model.mark[i])
                {
                    <label for="@buf"><img width="30px" class="star-img" src="~/img/star_t.png" /></label>
                }
                else
                {
                    <label for="@buf"><img width="30px" class="star-img" src="~/img/star_f.png" /></label>
                }
                <input id="@buf" asp-for="@Model.mark[i]" class="mark-check d-none mr-1" />
            }
            <input type="hidden" asp-for="@Model.Id" />
            <button class="btn btn-default btn-primary p-1 ml-3" type="submit">Send</button>
        </form>
    </div>
</div>
<div class="d-flex p-3 border mt-3">
    @{ bool ourCompany = User.Identity.Name == Model.User; }
    <a class="btn btn-default btn-primary mr-3" href="#" id="info">Info</a>
    <a class="btn btn-default btn-primary mr-3" href="#" id="news">News</a>
    @if (ourCompany)
    {
        <a class="btn btn-default btn-primary mr-3" href="#" id="add-news">Add news</a>
    }
    <a class="btn btn-default btn-primary mr-3" href="#" id="bonuses">Bonuses</a>
    @if (ourCompany)
    {
        <a class="btn btn-default btn-primary mr-3" href="#" id="add-bonus">Add bonus</a>
        <script>
            document.getElementById("add-news").addEventListener("click", function () { SwitchSection(4); });
            document.getElementById("add-bonus").addEventListener("click", function () { SwitchSection(5); });
        </script>
    }
    <a class="btn btn-default btn-primary mr-3" href="#" id="comments">Comments</a>
</div>
<div class="main-section p-3 border mt-3 clearfix">
    <div class="d-block mb-3">
        <iframe id="embedded_video" style="display: block; min-width: 320px; min-height: 220px; width: 75%; margin: 0 auto" src="@Model.Video" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    </div>
    <p style="white-space: pre-line" id="markdown-text"></p>
</div>
<div class="main-section p-3 border mt-3 clearfix d-none">
    @for (int i = Model.news.Length - 1; i >= 0; i--)
    {
        <div class="p-3 border rounded dark mb-3">
            @if (ourCompany)
            {
                <form asp-controller="News" asp-action="DeleteNews" method="post">
                    <input asp-for="deleteNewsID" type="hidden" value="@Model.news[i].id">
                    <input type="hidden" asp-for="Id" />
                    <button class="btn btn-lg btn-primary mt-3 mb-3" type="submit">Delete</button>
                </form>
            }
            <div class="d-flex align-items-center">
                <img class="mr-3" src="@Model.news[i].Image" style="max-width: 300px; max-height: 150px;" />
                <h3>@Model.news[i].Name</h3>
            </div>
            <p style="white-space: pre-line" class="news-text">@Model.news[i].Description</p>
        </div>
    }
</div>
<div class="main-section p-3 border mt-3 clearfix d-none">
    @for (int i = Model.bonuses.Length - 1; i >= 0; i--)
    {
        <div class="p-3 border rounded dark mb-3">
            @if (ourCompany)
            {
                <form asp-controller="Bonuses" asp-action="DeleteBonus" method="post">
                    <input asp-for="deleteBonusID" type="hidden" value="@Model.bonuses[i].id">
                    <input type="hidden" asp-for="Id" />
                    <button class="btn btn-lg btn-primary mt-3 mb-3" type="submit">Delete</button>
                </form>
            }
            <h3>Name: @Model.bonuses[i].Name Sum: @Model.bonuses[i].Sum</h3>
            <p style="white-space: pre-line">@Model.bonuses[i].Description</p>
            <form asp-controller="Bonuses" asp-action="Pay" method="post">
                <input type="hidden" asp-for="payID" value="@Model.bonuses[i].id" />
                <input type="hidden" asp-for="Id" />
                <button class="btn btn-lg btn-primary mt-3 mb-3" type="submit">Pay</button>
            </form>
        </div>
    }
</div>
<div class="main-section p-3 border mt-3 clearfix d-none">
    <div>
        <textarea rows=3 id="comment" class="form-control mb-3" placeholder="Comment text"></textarea>
        <button class="btn btn-default btn-primary mb-3" id="sendBtn">Send</button>
    </div>
    <div id="comments-list">
        @for (int i = 0; i < Model.comments.Length; i++)
        {
            <div class="border rounded p-3 mb-3">
                <h2 class="author">@Model.comments[i].Author</h2>
                <p class="text-context">@Model.comments[i].Text</p>
                <span>Rating: </span>
                <span class="rating">@Model.comments[i].Rating</span>
                <a class="like ml-3"><img src="~/img/like.png" width="18" /></a>
                <a class="dislike ml-3"><img src="~/img/dislike.png" width="18" /></a>
                <input type="hidden" class="comment-id" value="@Model.comments[i].id" />
            </div>
        }
    </div>
</div>

<div class="main-section p-3 border mt-3 clearfix d-none">
    <form asp-controller="News" asp-action="AddNews" method="post">
        <label asp-for="addNews.Name" class="text-muted mt-3"></label>
        <input asp-for="addNews.Name" class="form-control col-md-6" placeholder="Name">
        <span asp-validation-for="addNews.Name" class="d-block"></span>

        <label asp-for="addNews.Description" class="text-muted mt-3"></label>
        <textarea rows=15 asp-for="addNews.Description" class="form-control" placeholder="Description"></textarea>
        <span asp-validation-for="addNews.Description" class="d-block"></span>

        <a class="btn btn-default btn-primary mb-3 mt-3" onclick="document.querySelector('.image-loader').click()" href="#">Load image</a>
        <input class="image-loader" style="visibility: collapse; width: 0px;" type="file" onchange="upload(this.files[0])">
        <img class="company-image d-block" style="max-width: 300px; max-height: 150px;" src="@Model.addNews.Image" />

        <input type="hidden" asp-for="Id" />
        <input id="company-image" asp-for="addNews.Image" hidden />

        <button class="btn btn-lg btn-primary btn-block mt-3 mb-3" type="submit">Add</button>
    </form>
</div>
<div class="main-section p-3 border mt-3 clearfix d-none">
    <form asp-controller="Bonuses" asp-action="AddBonus" method="post">
        <label asp-for="addBonus.Name" class="text-muted mt-3"></label>
        <input asp-for="addBonus.Name" class="form-control col-md-6" placeholder="Name">
        <span asp-validation-for="addBonus.Name" class="d-block"></span>

        <label asp-for="addBonus.Description" class="text-muted mt-3"></label>
        <textarea rows=15 asp-for="addBonus.Description" class="form-control" placeholder="Description"></textarea>
        <span asp-validation-for="addBonus.Description" class="d-block"></span>

        <label asp-for="addBonus.Sum" class="text-muted mt-3"></label>
        <input type="number" asp-for="addBonus.Sum" class="form-control col-md-6" placeholder="Name">
        <span asp-validation-for="addBonus.Sum" class="d-block"></span>

        <input type="hidden" asp-for="Id" />

        <button class="btn btn-lg btn-primary btn-block mt-3 mb-3" type="submit">Add</button>
    </form>
</div>
<div class="main-section p-3 border mt-3 clearfix d-none">
    <form asp-controller="Bonuses" asp-action="AddBonus" method="post">
        <label asp-for="addBonus.Name" class="text-muted mt-3"></label>
        <input asp-for="addBonus.Name" class="form-control col-md-6" placeholder="Name">
        <span asp-validation-for="addBonus.Name" class="d-block"></span>

        <label asp-for="addBonus.Description" class="text-muted mt-3"></label>
        <textarea rows=15 asp-for="addBonus.Description" class="form-control" placeholder="Description"></textarea>
        <span asp-validation-for="addBonus.Description" class="d-block"></span>

        <label asp-for="addBonus.Sum" class="text-muted mt-3"></label>
        <input type="number" asp-for="addBonus.Sum" class="form-control col-md-6" placeholder="Name">
        <span asp-validation-for="addBonus.Sum" class="d-block"></span>

        <input type="hidden" asp-for="Id" />

        <button class="btn btn-lg btn-primary btn-block mt-3 mb-3" type="submit">Add</button>
    </form>
</div>

<script src="~/js/markdown.js"></script>
<script src="~/js/signalr.min.js"></script>
<script src="~/js/CommentHub.js" defer></script>
<script src="~/js/ShowCompany.js" defer></script>

Views/Company/NotFound.cshtml
<h2>Company was not found</h2>